# Generated by Django 4.0.4 on 2022-06-03 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cientificas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cientificas',
            name='foto',
        ),
    ]
