# Generated by Django 4.0.4 on 2022-06-03 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cientificas', '0002_remove_cientificas_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='cientificas',
            name='foto',
            field=models.ImageField(blank=True, upload_to='fotos'),
        ),
    ]
