# Generated by Django 4.0.5 on 2022-06-09 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0001_initial'),
        ('cientificas', '0003_cientificas_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='cientificas',
            name='area',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='area.area'),
            preserve_default=False,
        ),
    ]
